from abc import ABC, abstractmethod
from typing import AsyncGenerator, List, Dict
from src.domain.entities import ConversationSession

class ILLMProvider(ABC):
    """Port for Language Model services."""
    
    @abstractmethod
    async def generate_stream(
        self, 
        messages: List[Dict[str, str]], 
        system_prompt: str
    ) -> AsyncGenerator[str, None]:
        """
        Generates text in streaming based on chat history.
        
        Args:
            messages: List of chat messages (role and content).
            system_prompt: The instructions for the AI behavior.
            
        Yields:
            Tokens of text generated by the model.
        """
        pass



class IEmbeddingProvider(ABC):
    """Port for text embedding services."""
    
    @abstractmethod
    def embed_text(self, text: str) -> List[float]:
        """Convert text into a vector representation."""
        pass

    @abstractmethod
    def embed_batch(self, texts: List[str]) -> List[List[float]]:
        """Convert a list of texts into vector representations."""
        pass

class IVectorStore(ABC):
    """Port for Vector Storage and retrieval."""
    
    @abstractmethod
    async def search(self, query_vector: List[float], company_id: str, limit: int = 5) -> List[Dict]:
        """Search for similar contexts filtering by company_id."""
        pass

    @abstractmethod
    async def upsert(self, points: List[Dict]) -> bool:
        """
        Add or update points in the vector store.
        Each point should contain: id, vector, and payload (with company_id).
        """
        pass

    @abstractmethod
    async def delete(self, company_id: str, filter_metadata: Dict = None) -> bool:
        """
        Delete points filtering by company_id and optionally other metadata.
        This is crucial for removing obsolete information.
        """
        pass

class ISessionRepository(ABC):
    """Port for persisting conversation sessions."""
    
    @abstractmethod
    def get_session(self, session_id: str) -> Optional[ConversationSession]:
        """Retrieve a session by its ID."""
        pass

    @abstractmethod
    def save_session(self, session_id: str, session: ConversationSession) -> None:
        """Persist a session."""
        pass

    @abstractmethod
    def delete_session(self, session_id: str) -> None:
        """Remove a session from storage."""
        pass

class IPromptRepository(ABC):
    """Port for managing dynamic system prompts."""
    
    @abstractmethod
    def get_prompt_for_company(self, company_id: str, default_prompt: str) -> str:
        """Retrieve a specific prompt based on the company."""
        pass

class ITTSProvider(ABC):
    """Port for Text-to-Speech services."""
    
    @abstractmethod
    async def synthesize_stream(
        self, 
        text_stream: AsyncGenerator[str, None]
    ) -> AsyncGenerator[bytes, None]:
        """
        Receives a text stream and returns an audio stream.
        
        Args:
            text_stream: An async generator of text tokens.
            
        Yields:
            Chunks of audio bytes (PCM).
        """
        pass
