from abc import ABC, abstractmethod
from typing import AsyncGenerator, List, Dict

class ILLMProvider(ABC):
    """Port for Language Model services."""
    
    @abstractmethod
    async def generate_stream(
        self, 
        messages: List[Dict[str, str]], 
        system_prompt: str
    ) -> AsyncGenerator[str, None]:
        """
        Generates text in streaming based on chat history.
        
        Args:
            messages: List of chat messages (role and content).
            system_prompt: The instructions for the AI behavior.
            
        Yields:
            Tokens of text generated by the model.
        """
        pass

class ISTTProvider(ABC):
    """Port for Speech-to-Text services."""
    
    @abstractmethod
    async def transcribe(self, audio: bytes) -> str:
        """
        Converts an audio buffer to text.
        
        Args:
            audio: Raw audio bytes.
            
        Returns:
            The transcribed text.
        """
        pass

class ITTSProvider(ABC):
    """Port for Text-to-Speech services."""
    
    @abstractmethod
    async def synthesize_stream(
        self, 
        text_stream: AsyncGenerator[str, None]
    ) -> AsyncGenerator[bytes, None]:
        """
        Receives a text stream and returns an audio stream.
        
        Args:
            text_stream: An async generator of text tokens.
            
        Yields:
            Chunks of audio bytes (PCM).
        """
        pass
